baseURL: https://dehsi2021.netlify.app/
languageCode: en-us
defaultContentLanguage: en
title: Digital Education Hub Summer Institute 2021
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

#permalinks:
#  post: /:filename/

imaging:
  quality: 99

params:
  description: The Digital Education Hub Summer Institute Online Workbook.
  homeMetaContent: The Digital Education Hub Summer Institute Online Workbook.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  moveFooterToHeader: false
  logoAlt: "DEH Summer Institute Logo"
  customCss:
    - css/icons.css
  #  - css/custom_02.css
  #customJs:
  #  - js/custom_01.js
  #  - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Background
      url: /background/
      weight: 2
    - name: Day 1
      url: /day1/
      weight: 3
    - name: Day 2
      url: /day2/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
